# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

language: generic
sudo: required
dist: trusty

os:
  - linux

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - LAZ_VER=1.8.2 LAZ_ENV=linux LAZ_OPT="--os=linux --cpu=x86_64"

before_deploy:
      - git config --local user.name "Travis CI"
      - git config --local user.email "matiasevara@gmail.com"
      - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
      - git tag $GIT_TAG -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file: 
    - ./Tachyon.tar.gz
  on:
     branch: master
  skip_cleanup: true

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &
  - chmod +x ./ci/travis.install.py
  - chmod +x ./src/Build.sh
  - chmod +x ./setup.sh

install:
  - ./ci/travis.install.py
  - ./setup.sh

script:
  - cd ./src
  - ./Build.sh
  - cd ..
  - cp ./src/Tachyon.bin .
  - cp ./src/Tachyon.sh .
  - cp ./src/toro-kvm-network.xml .
  - cp ./src/qemu-ifup .
  - mkdir TachyonFiles
  - cp ./src/TachyonFiles/index.html ./TachyonFiles/
  - tar -czvf Tachyon.tar.gz Tachyon.bin install.sh Tachyon.sh toro-kvm-network.xml qemu-ifup ./TachyonFiles/index.html
 
notifications:
  email:
    on_success: false
    on_failure: false
